# Generated by Django 4.1.7 on 2023-10-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hasil',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nilai2',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
