# Generated by Django 4.1.7 on 2023-11-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testmodule', '0002_user_hasil_user_nilai2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hasil',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='nilai',
            field=models.CharField(max_length=30, verbose_name='nilainilai'),
        ),
    ]
