# Generated by Django 4.1.7 on 2024-01-17 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_direktorat_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='images/avatar.png', upload_to='profile_avatars'),
        ),
    ]
