# Generated by Django 4.1.7 on 2024-01-17 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_profile_direktorat_satker_profile_satker'),
    ]

    operations = [
        migrations.CreateModel(
            name='reg_district',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kecamatan', models.CharField(max_length=10)),
                ('nama_kecamatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reg_provinces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_provinsi', models.CharField(max_length=10)),
                ('nama_provinsi', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='satker',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='reg_villages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_desa', models.CharField(max_length=10)),
                ('nama_desa', models.CharField(max_length=100)),
                ('kode_kecamatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.reg_district')),
            ],
        ),
        migrations.CreateModel(
            name='reg_regencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_kabupaten', models.CharField(max_length=10)),
                ('nama_kabupaten', models.CharField(max_length=100)),
                ('kode_provinsi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.reg_provinces')),
            ],
        ),
        migrations.AddField(
            model_name='reg_district',
            name='kode_kabupaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.reg_regencies'),
        ),
    ]
