# Generated by Django 4.1.7 on 2024-01-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_reg_district_reg_provinces_satker_level_reg_villages_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('psm', 'PSM'), ('dayatif', 'Dayatif')], max_length=12, null=True),
        ),
    ]
