# Generated by Django 4.1.7 on 2024-02-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['id'], 'verbose_name': 'Profile User', 'verbose_name_plural': 'Daftar Profile User'},
        ),
        migrations.AlterModelOptions(
            name='reg_district',
            options={'ordering': ['nama_kecamatan'], 'verbose_name': 'Kecamatan', 'verbose_name_plural': 'Daftar Kecamatan'},
        ),
        migrations.AlterModelOptions(
            name='reg_provinces',
            options={'ordering': ['nama_provinsi'], 'verbose_name': 'Provinsi', 'verbose_name_plural': 'Daftar Provinsi'},
        ),
        migrations.AlterModelOptions(
            name='reg_regencies',
            options={'ordering': ['nama_kabupaten'], 'verbose_name': 'Kabupaten', 'verbose_name_plural': 'Daftar Kabupaten'},
        ),
        migrations.AlterModelOptions(
            name='reg_villages',
            options={'ordering': ['nama_desa'], 'verbose_name': 'Desa', 'verbose_name_plural': 'Daftar Desa'},
        ),
        migrations.AlterModelOptions(
            name='satker',
            options={'ordering': ['nama_satker'], 'verbose_name': 'Satuan Kerja', 'verbose_name_plural': 'Daftar Satuan Kerja'},
        ),
    ]
