# Generated by Django 3.2.24 on 2024-02-21 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='satker',
            name='kabupaten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satker', to='users.reg_regencies'),
        ),
        migrations.AddField(
            model_name='satker',
            name='provinsi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satker', to='users.reg_provinces'),
        ),
    ]
