# Generated by Django 3.2.24 on 2024-02-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240221_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='reg_district',
            name='geom',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='reg_district',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reg_district',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reg_provinces',
            name='geom',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='reg_provinces',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reg_provinces',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reg_regencies',
            name='geom',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='reg_regencies',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reg_regencies',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='reg_villages',
            name='geom',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='reg_villages',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reg_villages',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
