# Generated by Django 3.2.24 on 2024-03-25 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240221_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='satker',
            name='order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
