# Generated by Django 4.1.7 on 2024-03-28 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_satker_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='satker',
            name='satker_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
