# Generated by Django 3.2.24 on 2024-04-18 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_observasi'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatkerBNNK',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('satker_id', models.BigIntegerField()),
                ('nama_satker', models.CharField(max_length=12)),
                ('kabupaten_id', models.BigIntegerField()),
                ('jumlah_profil', models.BigIntegerField()),
            ],
            options={
                'db_table': 'users_satker_bnnk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SatkerBNNP',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('satker_id', models.BigIntegerField()),
                ('nama_satker', models.CharField(max_length=12)),
                ('provinsi_id', models.BigIntegerField()),
                ('jumlah_profil', models.BigIntegerField()),
            ],
            options={
                'db_table': 'users_satker_bnnp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SatkerPusat',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('satker_id', models.BigIntegerField()),
                ('nama_satker', models.CharField(max_length=12)),
                ('jumlah_profil', models.BigIntegerField()),
            ],
            options={
                'db_table': 'users_satker_pusat',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='notelp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
