# Generated by Django 3.2.24 on 2024-04-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_kegiatan_akun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan_akun',
            name='no_unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
