# Generated by Django 3.2.24 on 2024-04-18 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_kegiatan_akun_no_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='kegiatan_akun',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='kegiatan_akun',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
