# Generated by Django 3.2.24 on 2024-04-19 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20240418_1700'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uraian_kegiatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=100, null=True)),
                ('uraian_kegiatan', models.CharField(blank=True, max_length=100, null=True)),
                ('pj', models.CharField(blank=True, max_length=100, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('kegiatan_akun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kode_kegiatan_akun', to='users.kegiatan_akun')),
            ],
        ),
    ]
