# Generated by Django 3.2.24 on 2024-04-19 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_uraian_kegiatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kegiatan_akun',
            name='akun_kegiatan',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uraian_kegiatan',
            name='keterangan',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='uraian_kegiatan',
            name='uraian_kegiatan',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
