# Generated by Django 4.1.7 on 2024-01-21 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_data_responden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rentang_usia', models.CharField(max_length=30)),
                ('pendidikan_terkahir', models.CharField(max_length=30)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('jenis_kelamin', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_responden_survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pendidikan', models.CharField(max_length=30)),
                ('jawaban', models.TextField()),
                ('id_survei', models.IntegerField()),
                ('nama', models.CharField(max_length=30)),
                ('jenis_kelamin', models.CharField(max_length=30)),
                ('perusahaan', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pekerjaan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('url', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jam_awal', models.TimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=30)),
                ('tipe', models.CharField(max_length=30)),
                ('judul', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('jam_akhir', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_isi_survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('array_nilai_jawaban', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('data_mentahan', models.TextField()),
                ('sigma_nilai', models.FloatField()),
                ('id_data_responden', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survei.tbl_data_responden')),
            ],
        ),
    ]
