# Generated by Django 4.1.7 on 2024-01-23 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_data_survei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('tipe', models.CharField(choices=[('skm_life_skill', 'SKM Life Skill'), ('skm_tes_urine', 'SKM Tes Urine'), ('skm', 'SKM')], max_length=20)),
                ('daftar_pertanyaan', models.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
