# Generated by Django 4.1.7 on 2024-01-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0002_tbl_data_survei'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_data_survei',
            name='generate_kode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tbl_data_survei',
            name='jam_akhir',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_data_survei',
            name='jam_awal',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_data_survei',
            name='jumlah_responden',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_data_survei',
            name='status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_data_survei',
            name='tanggal',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tbl_isi_survei',
            name='id_data_survei',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='survei.tbl_data_survei'),
        ),
    ]
