# Generated by Django 4.1.7 on 2024-01-26 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0003_tbl_data_survei_generate_kode_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_data_survei',
            old_name='generate_kode',
            new_name='kode',
        ),
    ]
