# Generated by Django 4.1.7 on 2024-01-28 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0004_rename_generate_kode_tbl_data_survei_kode'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipeSurvei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('daftar_pertanyaan', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipe Survei',
                'verbose_name_plural': 'Daftar Tipe Survei',
                'ordering': ['nama'],
            },
        ),
        migrations.CreateModel(
            name='DataSurvei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('judul', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal', models.DateField(blank=True, null=True)),
                ('jam_awal', models.TimeField(blank=True, null=True)),
                ('jam_akhir', models.TimeField(blank=True, null=True)),
                ('jumlah_responden', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('kode', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('tipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survei', to='survei.tipesurvei')),
            ],
            options={
                'verbose_name': 'Data Survei',
                'verbose_name_plural': 'Daftar Data Survei',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataRespondenSurvei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis_kelamin', models.CharField(max_length=30)),
                ('rentang_usia', models.CharField(max_length=30)),
                ('pendidikan', models.CharField(max_length=30)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('pekerjaan', models.CharField(blank=True, max_length=100, null=True)),
                ('survei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responden', to='survei.datasurvei')),
            ],
            options={
                'verbose_name': 'Data Responden Survei',
                'verbose_name_plural': 'Daftar Data Responden Survei',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DataPengisianSurvei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('array_nilai_jawaban', models.TextField()),
                ('data_mentahan', models.TextField()),
                ('sigma_nilai', models.FloatField()),
                ('responden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_pengisian', to='survei.datarespondensurvei')),
                ('survei', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_pengisian', to='survei.datasurvei')),
            ],
            options={
                'verbose_name': 'Data Pengisian Survei',
                'verbose_name_plural': 'Daftar Data Pengisian Survei',
                'ordering': ['-updated_at'],
            },
        ),
    ]
