# Generated by Django 4.1.7 on 2024-01-29 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0005_tipesurvei_datasurvei_datarespondensurvei_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasurvei',
            options={'ordering': ['-tanggal'], 'verbose_name': 'Data Survei', 'verbose_name_plural': 'Daftar Data Survei'},
        ),
        migrations.RenameField(
            model_name='datasurvei',
            old_name='status',
            new_name='status_pengiriman',
        ),
        migrations.AlterField(
            model_name='datarespondensurvei',
            name='jenis_kelamin',
            field=models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=15),
        ),
        migrations.AlterField(
            model_name='datarespondensurvei',
            name='pendidikan',
            field=models.CharField(choices=[('Doktor (S3)', 'Doktor (S3)'), ('Magister (S2)', 'Magister (S2)'), ('Sarjana (S1)', 'Sarjana (S1)'), ('Diploma (D1-D4)', 'Diploma (D1-D4)'), ('SMA/SMK/MA', 'SMA/SMK/MA'), ('SMP/MTs', 'SMP/MTs')], max_length=50),
        ),
        migrations.AlterField(
            model_name='datarespondensurvei',
            name='rentang_usia',
            field=models.CharField(choices=[('12-25', '12 - 25 tahun'), ('26-45', '26 - 45 tahun'), ('46-65', '46 - 65 tahun')], max_length=30),
        ),
    ]
