# Generated by Django 4.1.7 on 2024-01-29 06:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survei', '0006_alter_datasurvei_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_isi_survei',
            name='id_data_responden',
        ),
        migrations.RemoveField(
            model_name='tbl_isi_survei',
            name='id_data_survei',
        ),
        migrations.DeleteModel(
            name='tbl_responden_survei',
        ),
        migrations.DeleteModel(
            name='tbl_survei',
        ),
        migrations.AddField(
            model_name='datapengisiansurvei',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_pengisian_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datapengisiansurvei',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_pengisian_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datarespondensurvei',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_responden_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datarespondensurvei',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_responden_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasurvei',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_survei_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datasurvei',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_survei_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipesurvei',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipe_survei_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipesurvei',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipe_survei_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='tbl_data_responden',
        ),
        migrations.DeleteModel(
            name='tbl_data_survei',
        ),
        migrations.DeleteModel(
            name='tbl_isi_survei',
        ),
    ]
