# Generated by Django 4.1.7 on 2024-01-29 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survei', '0007_remove_tbl_isi_survei_id_data_responden_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasurvei',
            name='dikirimkan_kepada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daftar_data_survei', to=settings.AUTH_USER_MODEL),
        ),
    ]
