# Generated by Django 4.1.7 on 2024-01-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0009_rename_jumlah_responden_datasurvei_batas_responden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasurvei',
            options={'ordering': ['id'], 'verbose_name': 'Data Survei', 'verbose_name_plural': 'Daftar Data Survei'},
        ),
        migrations.AlterField(
            model_name='datapengisiansurvei',
            name='data_mentahan',
            field=models.JSONField(),
        ),
    ]
