# Generated by Django 4.1.7 on 2024-02-02 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0011_rename_tanggal_datasurvei_tanggal_akhir_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapengisiansurvei',
            name='responden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='data_pengisian', to='survei.datarespondensurvei'),
        ),
    ]
