# Generated by Django 3.2.24 on 2024-02-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_is_admin'),
        ('survei', '0012_alter_datapengisiansurvei_responden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datasurvei',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='datasurvei',
            name='satker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='survei', to='users.satker'),
        ),
    ]
