# Generated by Django 3.2.24 on 2024-03-01 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0014_datasurvei_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarespondensurvei',
            name='alamat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datarespondensurvei',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='datarespondensurvei',
            name='handphone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
