# Generated by Django 3.2.24 on 2024-04-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0016_alter_datarespondensurvei_handphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipesurvei',
            name='direktorat',
            field=models.CharField(choices=[('psm', 'PSM'), ('dayatif', 'Dayatif')], default='psm', max_length=12),
        ),
    ]
