# Generated by Django 3.2.24 on 2024-04-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0017_tipesurvei_direktorat'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipesurvei',
            name='kode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
