# Generated by Django 3.2.24 on 2024-05-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survei', '0019_dataintelijenrespondensurvei_dataintelijensumbersurvei_dataintelijensurvei'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataintelijenrespondensurvei',
            name='alamat',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijenrespondensurvei',
            name='nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijenrespondensurvei',
            name='nik',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='desa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='nama_desa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='nama_kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='nama_kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='nama_petugas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nama Petugas'),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='nama_provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='nik_petugas',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Petugas'),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='provinsi',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='tanggal_wawancara',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Dilaksanakan Wawancara'),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='waktu_akhir',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='waktu_mulai',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataintelijensurvei',
            name='wilayah',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
