# Generated by Django 4.1.7 on 2024-01-17 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='literasi',
            name='kategori',
            field=models.CharField(choices=[('1', 'Petunjuk Kerja'), ('2', 'e-Book'), ('3', 'Bahan Sosialisasi'), ('4', 'Materi Pelatihan')], default='1', max_length=1),
        ),
    ]
