# Generated by Django 4.1.7 on 2024-01-28 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0002_literasi_kategori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='literasi',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Literasi', 'verbose_name_plural': 'Daftar Literasi'},
        ),
        migrations.RenameField(
            model_name='literasi',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='literasi',
            old_name='last_updated',
            new_name='updated_at',
        ),
    ]
