# Generated by Django 4.1.7 on 2024-03-15 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0004_rename_judul_literasi_judul_literasi_jumlah_diunduh_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='literasi',
            name='tags',
        ),
        migrations.AlterField(
            model_name='literasi',
            name='kategori',
            field=models.CharField(choices=[('audio', 'Audio'), ('buku', 'Buku'), ('video', 'Video'), ('video_youtube', 'Video Youtube')], default='1', max_length=15),
        ),
        migrations.AlterField(
            model_name='literasi',
            name='status',
            field=models.CharField(choices=[('archived', 'ARCHIVED'), ('draft', 'DRAFT'), ('published', 'PUBLISHED')], default='1', max_length=15),
        ),
    ]
