# Generated by Django 3.2.24 on 2024-03-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0005_remove_literasi_tags_alter_literasi_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literasi',
            name='kategori',
            field=models.CharField(choices=[('video_youtube', 'Video Youtube'), ('audio', 'Audio'), ('buku', 'Buku'), ('video', 'Video')], default='buku', max_length=15),
        ),
        migrations.AlterField(
            model_name='literasi',
            name='status',
            field=models.CharField(choices=[('published', 'PUBLISHED'), ('archived', 'ARCHIVED'), ('draft', 'DRAFT')], default='draft', max_length=15),
        ),
    ]
