# Generated by Django 3.2.24 on 2024-03-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('literasi', '0006_auto_20240318_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='literasi',
            name='kategori',
            field=models.CharField(choices=[('video_youtube', 'Video Youtube'), ('buku', 'Buku'), ('video', 'Video'), ('audio', 'Audio')], default='buku', max_length=15),
        ),
        migrations.AlterField(
            model_name='literasi',
            name='status',
            field=models.CharField(choices=[('archived', 'ARCHIVED'), ('published', 'PUBLISHED'), ('draft', 'DRAFT')], default='draft', max_length=15),
        ),
    ]
