# Generated by Django 4.1.7 on 2024-01-28 15:44

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('judul', models.TextField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150, null=True)),
                ('isi_berita', ckeditor.fields.RichTextField()),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('tags', models.TextField(max_length=1000)),
                ('gambar_utama', models.ImageField(upload_to='upload/files/berita/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berita_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Berita',
                'verbose_name_plural': 'Daftar Berita',
            },
        ),
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Daftar Kategori',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Daftar Tag',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='upload/files/berita/')),
                ('berita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='berita.berita')),
            ],
        ),
        migrations.AddField(
            model_name='berita',
            name='kategori',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='berita.kategori'),
        ),
        migrations.AddField(
            model_name='berita',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='berita_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
