# Generated by Django 4.1.7 on 2024-03-15 03:30

import berita.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_auto_20240229_1100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berita',
            name='tanggal',
        ),
        migrations.AlterField(
            model_name='berita',
            name='gambar_utama',
            field=models.ImageField(upload_to='upload/files/berita/', validators=[berita.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='berita',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=12),
        ),
    ]
