# Generated by Django 3.2.24 on 2024-03-18 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20240221_1717'),
        ('kegiatan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSM_RAKERNIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_awal', models.DateField(blank=True, default='2024-03-18', null=True, verbose_name='Tanggal Awal Kegiatan')),
                ('tanggal_akhir', models.DateField(blank=True, default='2024-03-18', null=True, verbose_name='Tanggal Akhir Kegiatan')),
                ('deskripsi', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('kendala', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('kesimpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('dokumentasi', models.FileField(upload_to='uploads/kegiatan/psm/rakernis/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_rakernis_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_rakernis_satker', to='users.satker', verbose_name='SATUAN KERJA PELAKSANA')),
                ('satker_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_rakernis_satker_target', to='users.satker', verbose_name='SATUAN KERJA TARGET')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_rakernis_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM RAKERNIS',
                'verbose_name_plural': 'DAFTAR PSM RAKERNIS',
                'db_table': 'kegiatan_psm_rakernis',
                'ordering': ['-updated_at'],
            },
        ),
    ]
