# Generated by Django 3.2.24 on 2024-03-18 05:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0002_psm_rakernis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_rakernis',
            name='tanggal_akhir',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
        migrations.AlterField(
            model_name='psm_rakernis',
            name='tanggal_awal',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Awal Kegiatan'),
        ),
    ]
