# Generated by Django 3.2.24 on 2024-03-19 02:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240221_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kegiatan', '0004_dayatif_pemetaan_potensi_nama_desa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayatif_pemetaan_potensi',
            name='desa',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_potensi',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_potensi',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_potensi',
            name='provinsi',
            field=models.CharField(blank=True, max_length=258, null=True),
        ),
        migrations.CreateModel(
            name='PSM_BINAAN_TEKNIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_awal', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Awal Kegiatan')),
                ('tanggal_akhir', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Akhir Kegiatan')),
                ('deskripsi', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('kendala', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kendala')),
                ('kesimpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kesimpulan')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(upload_to='uploads/kegiatan/psm/bintek/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_bintek_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_bintek_satker', to='users.satker', verbose_name='SATUAN KERJA PELAKSANA')),
                ('satker_target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_bintek_satker_target', to='users.satker', verbose_name='SATUAN KERJA TARGET')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_bintek_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM BINAAN TEKNIS',
                'verbose_name_plural': 'DAFTAR PSM BINAAN TEKNIS',
                'db_table': 'kegiatan_psm_binaan_teknis',
                'ordering': ['-updated_at'],
            },
        ),
    ]
