# Generated by Django 3.2.24 on 2024-03-19 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240221_1717'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kegiatan', '0005_auto_20240319_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAYATIF_BINAAN_TEKNIS2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_binaan_teknis2_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dayatif_binaan_teknis2_satker', to='users.satker', verbose_name='SATUAN KERJA PELAKSANA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_binaan_teknis2_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DAYATIF KEGIATAN BINAAN TEKNIS 2',
                'verbose_name_plural': 'DAFTAR DAYATIF KEGIATAN BINAAN TEKNIS 2',
                'db_table': 'kegiatan_dayatif_binaan_teknis2',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DAYATIF_BINAAN_TEKNIS2_KEGIATAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_awal', models.DateField(verbose_name='Tanggal Awal Kegiatan')),
                ('tanggal_akhir', models.DateField(verbose_name='Tanggal Akhir Kegiatan')),
                ('jumlah_hari_pelaksanaan', models.IntegerField(default=2, verbose_name='Jumlah Hari Pelaksanaan Kegiatan')),
                ('jumlah_peserta', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Peserta Kegiatan')),
                ('tujuan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tujuan')),
                ('kendala', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kendala')),
                ('kesimpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kesimpulan')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(upload_to='uploads/kegiatan/dayatif/binaan_teknis2/')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_binaan_teknis2', to='kegiatan.dayatif_binaan_teknis2')),
                ('satker_target', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='dayatif_binaan_teknis2_satker_target', to='users.satker', verbose_name='SATUAN KERJA TARGET')),
            ],
            options={
                'verbose_name': 'DAYATIF SUB KEGIATAN BINAAN TEKNIS2',
                'verbose_name_plural': 'DAFTAR DAYATIF SUB KEGIATAN BINAAN TEKNIS2',
                'db_table': 'kegiatan_dayatif_binaan_teknis2_kegiatan',
                'ordering': ['-updated_at'],
            },
        ),
    ]
