# Generated by Django 4.1.7 on 2024-03-19 08:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20240221_1717'),
        ('kegiatan', '0006_dayatif_binaan_teknis2_dayatif_binaan_teknis2_kegiatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan'),
        ),
        migrations.CreateModel(
            name='PSM_ASISTENSI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jumlah_kegiatan', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Kegiatan')),
                ('tanggal', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal')),
                ('jumlah_peserta', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Peserta')),
                ('stakeholder', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Stakeholder Yang Diasistensi Dalam Rangka Kotan')),
                ('deskripsi', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('kendala', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kendala')),
                ('kesimpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kesimpulan')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(upload_to='uploads/kegiatan/psm/asistensi/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_asistensi_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_asistensi_satker', to='users.satker', verbose_name='SATUAN KERJA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_asistensi_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM ASISTENSI',
                'verbose_name_plural': 'DAFTAR PSM ASISTENSI',
                'db_table': 'kegiatan_psm_asistensi',
                'ordering': ['-updated_at'],
            },
        ),
    ]
