# Generated by Django 4.1.7 on 2024-03-20 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0008_remove_dayatif_binaan_teknis2_kegiatan_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayatif_pemetaan_potensi',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan'),
        ),
    ]
