# Generated by Django 3.2.24 on 2024-03-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0009_dayatif_pemetaan_potensi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_rakernis',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan'),
        ),
    ]
