# Generated by Django 4.1.7 on 2024-03-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0010_psm_rakernis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayatif_binaan_teknis',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_potensi',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_stakeholder',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
        migrations.AlterField(
            model_name='dayatif_rapat_sinergi_stakeholder',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
    ]
