# Generated by Django 3.2.24 on 2024-03-21 02:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0011_auto_20240221_1717'),
        ('kegiatan', '0011_alter_dayatif_binaan_teknis_tanggal_akhir_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSM_TES_URINE_DETEKSI_DINI_PESERTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_peserta', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=15)),
                ('hasil_test', models.CharField(choices=[('P', 'Positif'), ('N', 'Negatif')], max_length=15)),
                ('alamat', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PSM_TES_URINE_DETEKSI_DINI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jumlah_kegiatan', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Kegiatan')),
                ('tanggal', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal')),
                ('nama_lingkungan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Nama Lingkungan')),
                ('hasil_tes_urine', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Hasil Tes Urine')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(upload_to='uploads/kegiatan/psm/asistensi/')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_test_urine_deteksi_dini_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_test_urine_deteksi_dini_satker', to='users.satker', verbose_name='SATUAN KERJA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_test_urine_deteksi_dini_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM TES URINE DETEKSI DINI',
                'verbose_name_plural': 'DAFTAR PSM TES URINE DETEKSI DINI',
                'db_table': 'kegiatan_psm_test_urine_deteksi_dini',
                'ordering': ['-updated_at'],
            },
        ),
    ]
