# Generated by Django 3.2.24 on 2024-03-22 02:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240221_1717'),
        ('kegiatan', '0013_psm_tes_urine_deteksi_dini_peserta_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psm_tes_urine_deteksi_dini',
            name='jumlah_kegiatan',
        ),
        migrations.RemoveField(
            model_name='psm_tes_urine_deteksi_dini',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='psm_tes_urine_deteksi_dini',
            name='satker_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_tes_urine_satker_target', to='users.satker', verbose_name='SATUAN KERJA TARGET'),
        ),
        migrations.AddField(
            model_name='psm_tes_urine_deteksi_dini',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan'),
        ),
        migrations.AddField(
            model_name='psm_tes_urine_deteksi_dini',
            name='tanggal_akhir',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
        migrations.AddField(
            model_name='psm_tes_urine_deteksi_dini',
            name='tanggal_awal',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Awal Kegiatan'),
        ),
    ]
