# Generated by Django 3.2.24 on 2024-03-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0014_auto_20240322_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_binaan_teknis',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan'),
        ),
    ]
