# Generated by Django 4.1.7 on 2024-03-24 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0015_psm_binaan_teknis_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayatif_pemetaan_potensi',
            name='jumlah_hari_pelaksanaan',
        ),
    ]
