# Generated by Django 3.2.24 on 2024-03-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0017_alter_psm_tes_urine_deteksi_dini_dokumentasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_tes_urine_deteksi_dini',
            name='dokumentasi',
            field=models.FileField(blank=True, upload_to='uploads/kegiatan/psm/tes_urine_deteksi_dini/'),
        ),
    ]
