# Generated by Django 3.2.24 on 2024-04-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0020_psm_rakor_pemetaan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSM_MONITORING_DAN_EVALUASI_SUPERVISI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_peserta', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=15)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.psm_tes_urine_deteksi_dini')),
            ],
        ),
    ]
