# Generated by Django 3.2.24 on 2024-04-01 06:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0013_satker_satker_order'),
        ('kegiatan', '0021_psm_monitoring_dan_evaluasi_supervisi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psm_monitoring_dan_evaluasi_supervisi',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PSM MONITORING DAN EVALUASI SUPERVISI KEGIATAN KOTAN', 'verbose_name_plural': 'DAFTAR PSM MONITORING DAN EVALUASI SUPERVISI KEGIATAN KOTAN'},
        ),
        migrations.RemoveField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='jabatan',
        ),
        migrations.RemoveField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='jenis_kelamin',
        ),
        migrations.RemoveField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='nama_peserta',
        ),
        migrations.RemoveField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='parent',
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_monev_supervisi_kegiatan_kotan_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='deskripsi_hasil',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='dokumentasi',
            field=models.FileField(blank=True, upload_to='uploads/kegiatan/psm/monev_supervisi_kegiatan_kotan/'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='nama_lingkungan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Nama Lingkungan Dan Satker'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='nilai_ikp',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Nilai IKP'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='satker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_monev_supervisi_kegiatan_kotan_satker', to='users.satker', verbose_name='SATUAN KERJA'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='simpulan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Simpulan'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='status_ikp',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='status_indeks',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Status Indeks Kemandirian Partisipasi'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='tanggal_akhir',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='tanggal_awal',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Awal Kegiatan'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='tindak_lanjut',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut'),
        ),
        migrations.AddField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_monev_supervisi_kegiatan_kotan_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='psm_monitoring_dan_evaluasi_supervisi',
            table='kegiatan_psm_monev_supervisi_kegiatan_kotan',
        ),
        migrations.CreateModel(
            name='PSM_MONITORING_DAN_EVALUASI_SUPERVISI_PESERTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_peserta', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-Laki'), ('P', 'Perempuan')], max_length=15)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.psm_tes_urine_deteksi_dini')),
            ],
        ),
    ]
