# Generated by Django 3.2.24 on 2024-04-02 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0022_auto_20240401_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_monitoring_dan_evaluasi_supervisi_peserta',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.psm_monitoring_dan_evaluasi_supervisi'),
        ),
    ]
