# Generated by Django 4.1.7 on 2024-04-02 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0023_alter_psm_monitoring_dan_evaluasi_supervisi_peserta_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayatif_pemetaan_stakeholder',
            name='stakeholder',
        ),
        migrations.AddField(
            model_name='dayatif_pemetaan_stakeholder',
            name='nama_desa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_pemetaan_stakeholder',
            name='nama_kabupaten',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_pemetaan_stakeholder',
            name='nama_kecamatan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_pemetaan_stakeholder',
            name='nama_provinsi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_pemetaan_stakeholder',
            name='stakeholders',
            field=models.JSONField(blank=True, null=True, verbose_name='Daftar Stakeholder'),
        ),
        migrations.AddField(
            model_name='dayatif_pemetaan_stakeholder',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan'),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_stakeholder',
            name='desa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_stakeholder',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_stakeholder',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_stakeholder',
            name='provinsi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
