# Generated by Django 3.2.24 on 2024-04-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0025_psm_audiensi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='status_ikp',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Status IKP'),
        ),
        migrations.AlterField(
            model_name='psm_monitoring_dan_evaluasi_supervisi',
            name='status_indeks',
            field=models.IntegerField(default=0, verbose_name='Status Indeks Kemandirian Partisipasi'),
        ),
    ]
