# Generated by Django 3.2.24 on 2024-04-02 09:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_observasi'),
        ('kegiatan', '0027_psm_konsolidasi_kebijakan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSM_PENGUMPULAN_DATA_IKOTAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanggal_awal', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Awal Kegiatan')),
                ('tanggal_akhir', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Akhir Kegiatan')),
                ('deskripsi_hasil', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('simpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Simpulan')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(blank=True, upload_to='uploads/kegiatan/psm/pengumpulan_data_ikotan/')),
                ('status', models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_pengumpulan_data_ikotan_created_by', to=settings.AUTH_USER_MODEL)),
                ('observasi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_pengumpulan_data_ikotan_observasi', to='users.observasi', verbose_name='Unit Observasi')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_pengumpulan_data_ikotan_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM MONITORING DAN EVALUASI SUPERVISI KEGIATAN KOTAN',
                'verbose_name_plural': 'DAFTAR PSM MONITORING DAN EVALUASI SUPERVISI KEGIATAN KOTAN',
                'db_table': 'kegiatan_psm_pengumpulan_data_ikotan',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='PSM_PENGUMPULAN_DATA_IKOTAN_PESERTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama_peserta', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.psm_pengumpulan_data_ikotan')),
            ],
        ),
    ]
