# Generated by Django 3.2.24 on 2024-04-02 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_observasi'),
        ('kegiatan', '0028_psm_pengumpulan_data_ikotan_psm_pengumpulan_data_ikotan_peserta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psm_pengumpulan_data_ikotan',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PSM PENGUMPULAN DATA IKOTAN', 'verbose_name_plural': 'DAFTAR PSM PENGUMPULAN DATA IKOTAN'},
        ),
        migrations.AddField(
            model_name='psm_pengumpulan_data_ikotan',
            name='satker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_pengumpulan_data_ikotan_satker', to='users.satker', verbose_name='SATUAN KERJA'),
        ),
    ]
