# Generated by Django 3.2.24 on 2024-04-03 01:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_observasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kegiatan', '0031_auto_20240403_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_sinkronisasi_kebijakan',
            name='dokumentasi',
            field=models.FileField(upload_to='uploads/kegiatan/psm/sinkronisasi_kebijakan/'),
        ),
        migrations.CreateModel(
            name='PSM_WORKSHOP_TEMATIK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jumlah_kegiatan', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Kegiatan')),
                ('tanggal_awal', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Awal Kegiatan')),
                ('tanggal_akhir', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Akhir Kegiatan')),
                ('tanggal', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal')),
                ('jumlah_peserta', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Peserta')),
                ('stakeholder', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Stakeholder Yang Diasistensi Dalam Rangka Kotan')),
                ('deskripsi', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('kendala', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kendala')),
                ('kesimpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kesimpulan')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(upload_to='uploads/kegiatan/psm/workshop_tematik/')),
                ('status', models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_workshop_tematik_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_workshop_tematik_satker', to='users.satker', verbose_name='SATUAN KERJA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_workshop_tematik_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM WORKSHOP TEMATIK',
                'verbose_name_plural': 'DAFTAR PSM WORKSHOP TEMATIK',
                'db_table': 'kegiatan_psm_workshop_tematik',
                'ordering': ['-updated_at'],
            },
        ),
    ]
