# Generated by Django 3.2.24 on 2024-04-03 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0032_auto_20240403_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psm_pengumpulan_data_ikotan_peserta',
            old_name='nama_peserta',
            new_name='nama_peserta_ikotan',
        ),
    ]
