# Generated by Django 3.2.24 on 2024-04-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0033_rename_nama_peserta_psm_pengumpulan_data_ikotan_peserta_nama_peserta_ikotan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psm_pengumpulan_data_ikotan_peserta',
            old_name='nama_peserta_ikotan',
            new_name='nama_peserta',
        ),
    ]
