# Generated by Django 3.2.24 on 2024-04-03 03:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_observasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kegiatan', '0034_rename_nama_peserta_ikotan_psm_pengumpulan_data_ikotan_peserta_nama_peserta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psm_pengumpulan_data_ikotan',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PSM DUKUNGAN STAKEHOLDER', 'verbose_name_plural': 'DAFTAR PSM DUKUNGAN STAKEHOLDER'},
        ),
        migrations.CreateModel(
            name='PSM_DUKUNGAN_STAKEHOLDER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alamat', models.JSONField()),
                ('jumlah_sasaran', models.IntegerField(default=0)),
                ('hasil_dampak', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('kesimpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Simpulan')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(blank=True, upload_to='uploads/kegiatan/psm/dukungan_stakeholder/')),
                ('status', models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_dukungan_stakeholder_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_dukungan_stakeholder_satker', to='users.satker', verbose_name='SATUAN KERJA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_dukungan_stakeholder_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM DUKUNGAN STAKEHOLDER',
                'verbose_name_plural': 'DAFTAR PSM DUKUNGAN STAKEHOLDER',
                'db_table': 'kegiatan_psm_dukungan_stakeholder',
                'ordering': ['-updated_at'],
            },
        ),
    ]
