# Generated by Django 3.2.24 on 2024-04-03 06:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_observasi'),
        ('kegiatan', '0035_auto_20240403_1007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='psm_workshop_penggiat',
            options={'ordering': ['-updated_at'], 'verbose_name': 'PSM WORKSHOP PENGGIAT', 'verbose_name_plural': 'DAFTAR PSM WORKSHOP PENGGIAT'},
        ),
        migrations.AddField(
            model_name='psm_dukungan_stakeholder',
            name='kegiatan',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='psm_dukungan_stakeholder',
            name='pemda',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.CreateModel(
            name='PSM_BIMTEK_P4GN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seri_pin_penggiat', models.IntegerField(default=0, verbose_name='No. Seri Pin Penggiat')),
                ('tanggal_awal', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Awal Kegiatan')),
                ('tanggal_akhir', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Tanggal Akhir Kegiatan')),
                ('stakeholder', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Stakeholder')),
                ('hasil_capaian', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Hasil Capaian')),
                ('kendala', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kendala')),
                ('kesimpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kesimpulan')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(upload_to='uploads/kegiatan/psm/bimtek_p4gn/')),
                ('status', models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_bimtek_p4gn_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_bimtek_p4gn_satker', to='users.satker', verbose_name='SATUAN KERJA PELAKSANA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_bimtek_p4gn_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM BIMBINGAN TEKNIS P4GN',
                'verbose_name_plural': 'DAFTAR PSM BIMBINGAN TEKNIS P4GN',
                'db_table': 'kegiatan_psm_bimtek_p4gn',
                'ordering': ['-updated_at'],
            },
        ),
    ]
