# Generated by Django 3.2.24 on 2024-04-03 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0036_auto_20240403_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_bimtek_p4gn',
            name='stakeholder',
            field=models.JSONField(blank=True, null=True, verbose_name='Stakeholders'),
        ),
        migrations.CreateModel(
            name='PSM_BIMTEK_P4GN_PESERTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nama', models.CharField(blank=True, max_length=100, null=True)),
                ('alamat', models.TextField(blank=True, max_length=1000, null=True)),
                ('no_telepon', models.CharField(blank=True, max_length=18, null=True)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], default='L', max_length=1, verbose_name='Jenis Kelamin')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kegiatan.psm_bimtek_p4gn')),
            ],
            options={
                'verbose_name': 'PSM PESERTA BIMBINGAN TEKNIS PENGGIAT P4GN',
                'verbose_name_plural': 'DAFTAR PSM PESERTA BIMBINGAN TEKNIS PENGGIAT P4GN',
                'db_table': 'kegiatan_psm_bimtek_p4gn_peserta',
                'ordering': ['-updated_at'],
            },
        ),
    ]
