# Generated by Django 3.2.24 on 2024-04-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0037_auto_20240403_1408'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psm_bimtek_p4gn',
            name='stakeholder',
        ),
        migrations.AddField(
            model_name='psm_bimtek_p4gn',
            name='peserta',
            field=models.JSONField(blank=True, null=True, verbose_name='Peserta'),
        ),
    ]
