# Generated by Django 3.2.24 on 2024-04-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0038_auto_20240403_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='bentuk',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Bentuk'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='dokumentasi',
            field=models.FileField(blank=True, null=True, upload_to='uploads/kegiatan/dayatif/dukungan_stakeholder/'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='jenis',
            field=models.CharField(choices=[('DSP', 'Dukungan Sarana Produksi'), ('DSSDM', 'Dukungan SDM')], default='DSP', max_length=50),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='jumlah',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Jumlah'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='jumlah_peserta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Peserta Yang Hadir'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='jumlah_sasaran',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Jumlah Sasaran'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='kawasan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kawasan Yang Diintervensi'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='kesimpulan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Simpulan'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='pengaruh',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Pengaruh/Manfaat'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='stakeholder',
            field=models.JSONField(blank=True, null=True, verbose_name='Daftar Stakeholder'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='tempat',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tempat'),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='tindak_lanjut',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut'),
        ),
    ]
