# Generated by Django 3.2.24 on 2024-04-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0039_auto_20240403_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayatif_dukungan_stakeholder',
            name='kawasan',
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='desa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='nama_desa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='nama_kabupaten',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='nama_kecamatan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='nama_provinsi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_dukungan_stakeholder',
            name='provinsi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
