# Generated by Django 3.2.24 on 2024-04-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0040_auto_20240403_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_bimtek_p4gn',
            name='nama_lingkungan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Nama Lingkungan'),
        ),
    ]
