# Generated by Django 3.2.24 on 2024-04-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0041_psm_bimtek_p4gn_nama_lingkungan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_bimtek_p4gn',
            name='seri_pin_penggiat',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No. Seri Pin Penggiat'),
        ),
    ]
