# Generated by Django 3.2.24 on 2024-04-04 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_observasi'),
        ('kegiatan', '0042_alter_psm_bimtek_p4gn_seri_pin_penggiat'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSM_KEGIATAN_LAINNYA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kegiatan', models.TextField(blank=True, null=True)),
                ('tempat', models.TextField(blank=True, null=True)),
                ('waktu_awal', models.TimeField()),
                ('waktu_akhir', models.TimeField()),
                ('lingkungan', models.TextField(blank=True, null=True)),
                ('jumlah_sasaran', models.IntegerField(default=0)),
                ('hasil_dampak', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Deskripsi Hasil')),
                ('kesimpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Simpulan')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(blank=True, upload_to='uploads/kegiatan/psm/kegiatan_lainnya/')),
                ('status', models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_kegiatan_lainnya_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_kegiatan_lainnya_satker', to='users.satker', verbose_name='SATUAN KERJA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='psm_kegiatan_lainnya_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PSM KEGIATAN LAINNYA',
                'verbose_name_plural': 'DAFTAR PSM KEGIATAN LAINNYA',
                'db_table': 'kegiatan_psm_kegiatan_lainnya',
                'ordering': ['-updated_at'],
            },
        ),
    ]
