# Generated by Django 3.2.24 on 2024-04-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0043_psm_kegiatan_lainnya'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='keterampilan_detail',
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='anggaran',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Anggaran'),
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='jumlah_peserta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Peserta Yang Hadir'),
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='nama_desa',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='nama_kabupaten',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='nama_kecamatan',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='nama_provinsi',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='peserta',
            field=models.JSONField(blank=True, null=True, verbose_name='Daftar Peserta'),
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='status',
            field=models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan'),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='desa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='keterampilan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='keterampilan'),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='provinsi',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir Kegiatan'),
        ),
    ]
