# Generated by Django 3.2.24 on 2024-04-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0044_auto_20240404_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayatif_dukungan_stakeholder',
            name='tempat',
        ),
        migrations.AlterField(
            model_name='psm_tes_urine_deteksi_dini_peserta',
            name='hasil_test',
            field=models.CharField(max_length=100),
        ),
    ]
