# Generated by Django 3.2.24 on 2024-04-05 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0045_auto_20240405_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_tes_urine_deteksi_dini_peserta',
            name='isi_parameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dayatif_dukungan_stakeholder',
            name='jenis',
            field=models.CharField(choices=[('DSP', 'Dukungan Sarana Produksi'), ('DSSDM', 'Dukungan SDM'), ('Lainnya', 'Dukungan Lainnya')], default='DSP', max_length=50),
        ),
        migrations.AlterField(
            model_name='psm_tes_urine_deteksi_dini_peserta',
            name='hasil_test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
