# Generated by Django 3.2.24 on 2024-04-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0046_auto_20240405_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayatif_dukungan_stakeholder',
            name='jumlah_peserta',
        ),
        migrations.AlterField(
            model_name='dayatif_dukungan_stakeholder',
            name='stakeholder',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Daftar Stakeholder'),
        ),
    ]
