# Generated by Django 3.2.24 on 2024-04-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0047_auto_20240415_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_tes_urine_deteksi_dini_peserta',
            name='keterangan_isi_parameter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
