# Generated by Django 3.2.24 on 2024-04-16 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_observasi'),
        ('kegiatan', '0049_psm_jadwal_kegiatan_tahunan'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='satker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_jadwal_kegiatan_tahunan_satker', to='users.satker', verbose_name='SATUAN KERJA'),
        ),
    ]
