# Generated by Django 3.2.24 on 2024-04-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0050_psm_jadwal_kegiatan_tahunan_satker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='jenis_giat',
        ),
        migrations.RemoveField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='lokasi',
        ),
        migrations.RemoveField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='penyelenggara',
        ),
        migrations.RemoveField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='target',
        ),
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='metode_kegiatan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='metode kegiatan'),
        ),
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='nama_kegiatan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='nama kegiatan'),
        ),
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='tempat_pelaksana',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='tempat kegiatan'),
        ),
        migrations.AlterField(
            model_name='dayatif_dukungan_stakeholder',
            name='jenis',
            field=models.CharField(choices=[('Dukungan Sarana Produksi', 'Dukungan Sarana Produksi'), ('Dukungan SDM', 'Dukungan SDM'), ('Dukungan Lainnya', 'Dukungan Lainnya')], default='DSP', max_length=50),
        ),
    ]
