# Generated by Django 3.2.24 on 2024-04-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0051_auto_20240416_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='jumlah_peserta',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jumlah Peserta'),
        ),
    ]
