# Generated by Django 3.2.24 on 2024-04-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0053_auto_20240416_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='anggaran',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='anggaran'),
        ),
    ]
