# Generated by Django 3.2.24 on 2024-04-17 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0055_psm_jadwal_kegiatan_tahunan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='tanggal_akhir',
        ),
        migrations.RemoveField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='tanggal_awal',
        ),
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='waktu_kegiatan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='waktu kegiatan'),
        ),
        migrations.AlterField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='status',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Status Pengiriman Kegiatan'),
        ),
    ]
