# Generated by Django 4.1.7 on 2024-04-17 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0014_observasi'),
        ('kegiatan', '0056_auto_20240417_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='DAYATIF_MONEV_DAYATIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0, verbose_name='Status Pengiriman Kegiatan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jenis', models.CharField(blank=True, choices=[('Monitoring dan Evaluasi Kinerja', 'Monitoring dan Evaluasi Kinerja'), ('Monitoring dan Evaluasi dalam rangka Pendampingan', 'Monitoring dan Evaluasi dalam rangka Pendampingan')], max_length=49, null=True, verbose_name='Jenis')),
                ('periode', models.CharField(blank=True, choices=[('Triwulan', 'Triwulan'), ('Semester', 'Semester'), ('Tahunan', 'Tahunan')], max_length=8, null=True, verbose_name='Periode')),
                ('tanggal_awal', models.DateField(verbose_name='Tanggal Awal Kegiatan')),
                ('tanggal_akhir', models.DateField(blank=True, null=True, verbose_name='Tanggal Akhir Kegiatan')),
                ('tempat', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tempat')),
                ('desa', models.CharField(blank=True, max_length=250, null=True)),
                ('kecamatan', models.CharField(blank=True, max_length=250, null=True)),
                ('kabupaten', models.CharField(blank=True, max_length=250, null=True)),
                ('provinsi', models.CharField(blank=True, max_length=250, null=True)),
                ('nama_desa', models.CharField(blank=True, max_length=150, null=True)),
                ('nama_kecamatan', models.CharField(blank=True, max_length=150, null=True)),
                ('nama_kabupaten', models.CharField(blank=True, max_length=150, null=True)),
                ('nama_provinsi', models.CharField(blank=True, max_length=150, null=True)),
                ('keterampilan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='keterampilan')),
                ('peserta', models.JSONField(blank=True, null=True, verbose_name='Daftar Peserta')),
                ('jumlah_peserta', models.IntegerField(blank=True, null=True, verbose_name='Jumlah Peserta Yang Hadir')),
                ('sinergi_desa', models.BooleanField(default=False, verbose_name='Sinergi Desa')),
                ('sinergi_ibm', models.BooleanField(default=False, verbose_name='Sinergi IBM')),
                ('hasil_skm_nilai', models.FloatField(blank=True, null=True, verbose_name='Hasil SKM Nilai')),
                ('hasil_skm_kategori', models.CharField(choices=[('buruk', 'Buruk'), ('cukup', 'Cukup'), ('baik', 'Baik'), ('sangat_baik', 'Sangat Baik')], default='cukup', max_length=11, verbose_name='Hasil SKM Kategori')),
                ('hasil_indeks_kewirausahaan_nilai', models.FloatField(blank=True, null=True, verbose_name='Hasil Indeks Kewirausahaan')),
                ('hasil_indeks_kewirausahaan_kategori', models.CharField(choices=[('buruk', 'Buruk'), ('cukup', 'Cukup'), ('baik', 'Baik'), ('sangat_baik', 'Sangat Baik')], default='cukup', max_length=11, verbose_name='Hasil SKM Kategori')),
                ('status_kerawanan_kawasan_awal_kategori', models.CharField(blank=True, max_length=250, null=True, verbose_name='Status Kerawanan Awal Kategori')),
                ('status_kerawanan_kawasan_akhir_nilai', models.FloatField(blank=True, null=True, verbose_name='Status Kerawanan Akhir Nilai IKKR')),
                ('status_kerawanan_kawasan_akhir_kategori', models.CharField(blank=True, max_length=250, null=True, verbose_name='Status Kerawanan Akhir Kategori')),
                ('status_kerawanan_kawasan_kepulihan', models.CharField(blank=True, max_length=250, null=True, verbose_name='Status Kerawanan Kepulihan')),
                ('kesimpulan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Kesimpulan')),
                ('tindak_lanjut', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tindak Lanjut')),
                ('dokumentasi', models.FileField(upload_to='uploads/kegiatan/dayatif/monev_dayatif/', verbose_name='Dokumentasi File')),
                ('gambar', models.FileField(null=True, upload_to='uploads/kegiatan/dayatif/monev_dayatif/gambar/', verbose_name='Dokumentasi Gambar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_monev_dayatif_created_by', to=settings.AUTH_USER_MODEL)),
                ('satker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dayatif_monev_dayatif_satker', to='users.satker', verbose_name='SATUAN KERJA PELAKSANA')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dayatif_monev_dayatif_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'DAYATIF MONEV DAYATIF',
                'verbose_name_plural': 'DAFTAR DAYATIF MONEV DAYATIF',
                'db_table': 'kegiatan_dayatif_monev_dayatif',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.DeleteModel(
            name='DAYATIF_MONITORING_DAN_EVALUASI',
        ),
    ]
