# Generated by Django 4.1.7 on 2024-04-18 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0057_dayatif_monev_dayatif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_kegiatan_lainnya',
            name='kode',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kode'),
        ),
        migrations.AddField(
            model_name='psm_kegiatan_lainnya',
            name='pendapatan',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pendapatan'),
        ),
    ]
