# Generated by Django 3.2.24 on 2024-04-18 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_kegiatan_akun_no_unit'),
        ('kegiatan', '0058_psm_kegiatan_lainnya_kode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='anggaran',
        ),
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='keterangan',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Keterangan'),
        ),
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='kode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='psm_jadwal_kegiatan_tahunan_kegiatan_akun', to='users.kegiatan_akun', verbose_name='KODE KEGIATAN AKUN'),
        ),
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='ordering_asc',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Urutan'),
        ),
        migrations.AddField(
            model_name='psm_jadwal_kegiatan_tahunan',
            name='pj',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='PJ'),
        ),
    ]
