# Generated by Django 4.1.7 on 2024-04-22 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kegiatan', '0064_remove_psm_bimtek_p4gn_peserta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DAYATIF_BIMBINGAN_TEKNIS_LIFESKILL_PESERTA',
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='gambar',
            field=models.FileField(null=True, upload_to='uploads/kegiatan/dayatif/bimbingan_teknis_lifeskill/gambar/', verbose_name='Dokumentasi Gambar'),
        ),
        migrations.AddField(
            model_name='dayatif_bimbingan_teknis_stakeholder',
            name='gambar',
            field=models.FileField(null=True, upload_to='uploads/kegiatan/dayatif/bimbingan_teknis_stakeholder/gambar/', verbose_name='Dokumentasi Gambar'),
        ),
        migrations.AddField(
            model_name='dayatif_binaan_teknis',
            name='gambar',
            field=models.FileField(null=True, upload_to='uploads/kegiatan/dayatif/binaan_teknis/gambar/', verbose_name='Dokumentasi Gambar'),
        ),
        migrations.AddField(
            model_name='dayatif_pemetaan_potensi',
            name='gambar',
            field=models.FileField(null=True, upload_to='uploads/kegiatan/dayatif/pemetaan_potensi/gambar/', verbose_name='Dokumentasi Gambar'),
        ),
        migrations.AddField(
            model_name='dayatif_pemetaan_potensi',
            name='potensi',
            field=models.JSONField(blank=True, null=True, verbose_name='Potensi SDA & SDM'),
        ),
        migrations.AddField(
            model_name='dayatif_pemetaan_stakeholder',
            name='gambar',
            field=models.FileField(null=True, upload_to='uploads/kegiatan/dayatif/pemetaan_stakeholder/gambar/', verbose_name='Dokumentasi Gambar'),
        ),
        migrations.AddField(
            model_name='dayatif_rapat_sinergi_stakeholder',
            name='gambar',
            field=models.FileField(null=True, upload_to='uploads/kegiatan/dayatif/rapat_sinergi_stakeholder/gambar/', verbose_name='Dokumentasi Gambar'),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_bimbingan_teknis_lifeskill_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='dokumentasi',
            field=models.FileField(upload_to='uploads/kegiatan/dayatif/bimbingan_teknis_lifeskill/', verbose_name='Dokumentasi File'),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_lifeskill',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_bimbingan_teknis_lifeskill_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_stakeholder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_bimbingan_teknis_stakeholder_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_stakeholder',
            name='dokumentasi',
            field=models.FileField(upload_to='uploads/kegiatan/dayatif/bimbingan_teknis_stakeholder/', verbose_name='Dokumentasi File'),
        ),
        migrations.AlterField(
            model_name='dayatif_bimbingan_teknis_stakeholder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_bimbingan_teknis_stakeholder_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_binaan_teknis',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_binaan_teknis_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_binaan_teknis',
            name='dokumentasi',
            field=models.FileField(upload_to='uploads/kegiatan/dayatif/binaan_teknis/', verbose_name='Dokumentasi File'),
        ),
        migrations.AlterField(
            model_name='dayatif_binaan_teknis',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_binaan_teknis_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_monev_dayatif',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_monev_dayatif_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_monev_dayatif',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_monev_dayatif_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_potensi',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_pemetaan_potensi_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_potensi',
            name='dokumentasi',
            field=models.FileField(upload_to='uploads/kegiatan/dayatif/pemetaan_potensi/', verbose_name='Dokumentasi File'),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_potensi',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_pemetaan_potensi_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_stakeholder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_pemetaan_stakeholder_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_stakeholder',
            name='dokumentasi',
            field=models.FileField(upload_to='uploads/kegiatan/dayatif/pemetaan_stakeholder/', verbose_name='Dokumentasi File'),
        ),
        migrations.AlterField(
            model_name='dayatif_pemetaan_stakeholder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_pemetaan_stakeholder_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_rapat_sinergi_stakeholder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_rapat_sinergi_stakeholder_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dayatif_rapat_sinergi_stakeholder',
            name='dokumentasi',
            field=models.FileField(upload_to='uploads/kegiatan/dayatif/rapat_sinergi_stakeholder/', verbose_name='Dokumentasi File'),
        ),
        migrations.AlterField(
            model_name='dayatif_rapat_sinergi_stakeholder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dayatif_rapat_sinergi_stakeholder_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
