# Generated by Django 4.1.7 on 2024-04-22 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20240419_1036'),
        ('kegiatan', '0067_auto_20240422_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psm_kegiatan_lainnya',
            name='kode',
        ),
        migrations.RemoveField(
            model_name='psm_kegiatan_lainnya',
            name='pendapatan',
        ),
        migrations.AddField(
            model_name='psm_kegiatan_lainnya',
            name='anggaran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Perencanaan Anggaran'),
        ),
        migrations.AddField(
            model_name='psm_kegiatan_lainnya',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='URL GDrive'),
        ),
        migrations.AddField(
            model_name='psm_kegiatan_lainnya',
            name='kegiatan_akun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.kegiatan_akun', verbose_name='Kode Kegiatan Akun'),
        ),
        migrations.AddField(
            model_name='psm_kegiatan_lainnya',
            name='penyerapan_anggaran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Penyerapan Anggaran'),
        ),
        migrations.AddField(
            model_name='psm_kegiatan_lainnya',
            name='uraian_kegiatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.uraian_kegiatan', verbose_name='Uraian Kegiatan'),
        ),
    ]
