# Generated by Django 3.2.24 on 2024-04-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0068_remove_psm_kegiatan_lainnya_kode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSM_TES_URINE_COUNT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_satker', models.CharField(max_length=255)),
                ('peserta_count_2021', models.IntegerField(default=0)),
                ('peserta_count_2022', models.IntegerField(default=0)),
                ('peserta_count_2023', models.IntegerField(default=0)),
                ('peserta_count_2024', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'v_kegiatan_psm_bimtek_p4gn_count',
                'managed': False,
            },
        ),
    ]
