# Generated by Django 3.2.24 on 2024-04-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0069_psm_tes_urine_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_binaan_teknis',
            name='anggaran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Perencanaan Anggaran'),
        ),
        migrations.AddField(
            model_name='psm_binaan_teknis',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tautan Dr'),
        ),
        migrations.AddField(
            model_name='psm_binaan_teknis',
            name='penyerapan_anggaran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Penyerapan Anggaran'),
        ),
        migrations.AlterField(
            model_name='psm_rakernis',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tautan Drive'),
        ),
        migrations.AlterModelTable(
            name='psm_tes_urine_count',
            table='kegiatan_psm_kegiatan_p4gn_count_view',
        ),
    ]
