# Generated by Django 3.2.24 on 2024-04-22 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0070_auto_20240422_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='psm_binaan_teknis',
            name='anggaran',
        ),
        migrations.RemoveField(
            model_name='psm_binaan_teknis',
            name='penyerapan_anggaran',
        ),
    ]
