# Generated by Django 3.2.24 on 2024-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0071_auto_20240422_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_binaan_teknis',
            name='anggaran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Perencanaan Anggaran'),
        ),
        migrations.AddField(
            model_name='psm_binaan_teknis',
            name='penyerapan_anggaran',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=18, verbose_name='Penyerapan Anggaran'),
        ),
    ]
