# Generated by Django 3.2.24 on 2024-04-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0072_auto_20240422_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psm_binaan_teknis',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tautan Drive'),
        ),
    ]
