# Generated by Django 3.2.24 on 2024-04-23 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0073_alter_psm_binaan_teknis_drive_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_rakor_pemetaan',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tautan Drive'),
        ),
    ]
