# Generated by Django 3.2.24 on 2024-04-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0077_auto_20240423_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_konsolidasi_kebijakan',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tautan Drive'),
        ),
    ]
