# Generated by Django 3.2.24 on 2024-04-23 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0081_auto_20240423_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_bimtek_p4gn',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tautan Drive'),
        ),
    ]
