# Generated by Django 3.2.24 on 2024-04-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0085_auto_20240423_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_workshop_tematik',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tautan Drive'),
        ),
    ]
