# Generated by Django 3.2.24 on 2024-04-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0087_auto_20240424_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_asistensi',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tautan Drive'),
        ),
    ]
