# Generated by Django 3.2.24 on 2024-04-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kegiatan', '0089_auto_20240424_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='psm_tes_urine_deteksi_dini',
            name='drive_url',
            field=models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tautan Drive'),
        ),
    ]
