# Generated by Django 4.1.7 on 2023-11-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_eform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_eform', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('nama_formulir', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('url', models.TextField(max_length=100)),
                ('tgl_akhir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='tbl_responden_eform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban_eform', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id_eform', models.IntegerField()),
                ('id_user', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
