# Generated by Django 4.1.7 on 2023-11-24 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_responden_survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('pendidikan', models.CharField(max_length=30)),
                ('jawaban', models.TextField()),
                ('id_survey', models.IntegerField()),
                ('nama', models.CharField(max_length=30)),
                ('jenis_kelamin', models.CharField(max_length=30)),
                ('perusahaan', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pekerjaan', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='tbl_survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('url', models.TextField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('jam_awal', models.TimeField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=30)),
                ('tipe', models.CharField(max_length=30)),
                ('judul', models.CharField(max_length=30)),
                ('status', models.BooleanField()),
                ('jam_akhir', models.TimeField()),
            ],
        ),
    ]
