# Generated by Django 4.1.7 on 2023-11-24 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="tbl_data_responden",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("rentang_usia", models.CharField(max_length=30)),
                ("pendidikan_terkahir", models.CharField(max_length=30)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("jenis_kelamin", models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="tbl_isi_survey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("array_nilai_jawaban", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("data_mentahan", models.TextField()),
                ("sigma_nilai", models.FloatField()),
                (
                    "id_data_responden",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.tbl_data_responden",
                    ),
                ),
            ],
        ),
    ]
