# Generated by Django 4.1.7 on 2024-01-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_survey_result_hasil'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='pemilik',
            field=models.CharField(choices=[('1', 'PSM'), ('2', 'DAYATF')], default='1', max_length=1),
        ),
    ]
