# Generated by Django 4.1.7 on 2024-01-18 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_survey_pemilik'),
    ]

    operations = [
        migrations.CreateModel(
            name='shortcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='survey',
            name='pemilik',
            field=models.CharField(choices=[('1', 'PSM'), ('2', 'DAYATIF')], default='1', max_length=1),
        ),
    ]
