# Generated by Django 4.1.7 on 2024-01-22 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_shortcode_alter_survey_pemilik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyshort',
            name='shortcode',
            field=models.CharField(max_length=8),
        ),
    ]
