# Generated by Django 3.2.24 on 2024-03-15 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20240221_1717'),
        ('survey', '0008_alter_survey_jsontext'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='satker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.satker'),
        ),
    ]
