# Generated by Django 3.2.24 on 2024-03-15 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0009_survey_satker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='pemilik',
        ),
        migrations.AddField(
            model_name='survey',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
