# Generated by Django 3.2.24 on 2024-03-15 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20240315_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='tanggal_akhir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='tanggal_awal',
            field=models.DateField(blank=True, null=True),
        ),
    ]
