# Generated by Django 3.2.24 on 2024-03-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_auto_20240315_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='kode',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
