# Generated by Django 3.2.24 on 2024-03-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0014_survey_result_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='limit',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
