# Generated by Django 3.2.24 on 2024-03-20 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_survey_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='survey',
            name='limit',
        ),
        migrations.AddField(
            model_name='survey',
            name='batasan',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
