# Generated by Django 4.1.7 on 2024-02-01 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='berita',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Berita', 'verbose_name_plural': 'Daftar Berita'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Daftar Kategori'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Daftar Tag'},
        ),
    ]
